#version 430

layout( local_size_x = 10, local_size_y = 10 ) in;

layout( binding = 0, rgba8) uniform image2D ColorImg;

uniform int width = 800;
uniform int height = 600;

void main() {
	float i = gl_GlobalInvocationID.x;
	float j = height - gl_GlobalInvocationID.y;
	float u = i / width;
    float v = j / height;
	vec4 color = vec4(u,v,0.2f,1);
	imageStore(ColorImg,ivec2(gl_GlobalInvocationID.xy), color);
}
